-- MySQL Script generated by MySQL Workbench
-- lun. 03 juil. 2017 14:39:42 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema XMLdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema XMLdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `XMLdatabase` DEFAULT CHARACTER SET utf8 ;
USE `XMLdatabase` ;

-- -----------------------------------------------------
-- Table `XMLdatabase`.`Program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XMLdatabase`.`Program` (
  `idProgram` INT NOT NULL AUTO_INCREMENT,
  `formation` VARCHAR(45) NULL,
  PRIMARY KEY (`idProgram`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XMLdatabase`.`Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XMLdatabase`.`Module` (
  `idModule` INT NOT NULL AUTO_INCREMENT,
  `objectif` VARCHAR(45) NULL,
  `prerequis` VARCHAR(45) NULL,
  `Materiel` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `group` VARCHAR(45) NULL,
  `Program_idProgram` INT NOT NULL,
  PRIMARY KEY (`idModule`),
  INDEX `fk_Module_Program_idx` (`Program_idProgram` ASC),
  CONSTRAINT `fk_Module_Program`
    FOREIGN KEY (`Program_idProgram`)
    REFERENCES `XMLdatabase`.`Program` (`idProgram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XMLdatabase`.`Sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XMLdatabase`.`Sequence` (
  `idSequence` INT NOT NULL AUTO_INCREMENT,
  `objectif` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `evaluation` VARCHAR(45) NULL,
  `Module_idModule` INT NOT NULL,
  PRIMARY KEY (`idSequence`),
  INDEX `fk_Sequence_Module1_idx` (`Module_idModule` ASC),
  CONSTRAINT `fk_Sequence_Module1`
    FOREIGN KEY (`Module_idModule`)
    REFERENCES `XMLdatabase`.`Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XMLdatabase`.`Activite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XMLdatabase`.`Activite` (
  `idActivite` INT NOT NULL AUTO_INCREMENT,
  `objectif` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `temps` VARCHAR(45) NULL,
  `sousObjectif` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `done` VARCHAR(45) NULL,
  `Sequence_idSequence` INT NOT NULL,
  PRIMARY KEY (`idActivite`),
  INDEX `fk_Activite_Sequence1_idx` (`Sequence_idSequence` ASC),
  CONSTRAINT `fk_Activite_Sequence1`
    FOREIGN KEY (`Sequence_idSequence`)
    REFERENCES `XMLdatabase`.`Sequence` (`idSequence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
